Repository boostcampaitech4lv23recsys2/level3_productserving-level3-recsys-08, pull requests merged in 2023-02, with the labels that each got.

#34 [Django] 추천 개선
  .gitignore
  Airflow/BaseLine/logs/scheduler/latest
  Content_based/content_based_4035_csv_to_pickle.ipynb
  Data/DataProcessing/Watch_link.ipynb
  Data/DataProcessing/movie_id_2_poster_file.ipynb
  Utils/Pickle/230131_watch_link_4679_rows.pickle
  Utils/Pickle/230201_characterid_to_hashtag.pickle
  Utils/Pickle/230201_fit_mbti_dict.pickle
  Utils/Pickle/content_based_4035.pickle
  Utils/Pickle/movie_random_select_final.pickle
  Utils/Pickle/movieid_to_poster_file.pickle
  Utils/__init__.py
  Utils/content_based_rec.py
  Utils/movie_select.py
  Utils/utils.py
  django/common/migrations/0001_initial.py
  django/common/models.py
  django/common/urls.py
  django/common/views.py
  django/static/css/netflix.css
  django/static/css/reset.css
  django/static/css/result_bootstrap.css
  django/static/css/result_movie.css
  django/static/css/scroll.css
  django/static/css/style.css
  django/static/css/test.css
  django/static/css/user_reset.css
  django/static/css/user_result_bootstrap.css
  django/static/css/user_style.css
  django/static/css/user_test.css
  django/static/grid.js
  django/static/js/footer.js
  django/static/js/infinite.min.js
  django/static/js/jquery.waypoints.min.js
  django/static/js/movie.js
  django/static/js/noframework.waypoints.min.js
  django/static/netflix.css
  django/static/spinner.js
  django/templates/base.html
  django/templates/common/signup.html
  django/templates/common/user_profile.html
  django/templates/index.html
  django/templates/navbar.html
  django/templates/test_rec/base.html
  django/templates/test_rec/enneagram.html
  django/templates/test_rec/enneagram2.html
  django/templates/test_rec/enneagram3.html
  django/templates/test_rec/footer.html
  django/templates/test_rec/main.html
  django/templates/test_rec/mbti.html
  django/templates/test_rec/movie.html
  django/templates/test_rec/nav.html
  django/templates/test_rec/result.html
  django/templates/test_rec/result_movie copy.html
  django/templates/test_rec/result_movie.html
  django/test_rec/combine/static/style.css
  django/test_rec/views.py
Labels: 조원준, 전해리, 이나현

#39 [Django] 인덱스 페이지
  django/common/urls.py
  django/common/views.py
  django/templates/base.html
  django/templates/common/mbti_info.html
  django/templates/common/user_profile.html
  django/templates/index.html
  django/templates/test_rec/base.html
Labels: 전해리, 채민수, 이나현

#40 [Feat][정의준] Airflow 일일 통계 dags 추가, git ignore 추가
  .gitignore
  Airflow/BaseLine/dags/summary.py
Labels: 조원준, 정의준

#42 [Airflow] UTC 시간, MLflow 추가, Real User interaction 추가
  Airflow/00_Fake_User_Recommend/Fake_User_Recommend.ipynb
  Airflow/BaseLine/dags/summary.py
  BaseLine/MLflow_test.ipynb
  BaseLine/mvti_recommend.ipynb
  BaseLine/mvti_recommend.py
  BaseLine/util.py
  requirements.txt
Labels: 조원준, 정의준

#44 [Django] MBTI별 인기순위 적용, 인덱스 페이지 유저 연결
  django/common/urls.py
  django/common/views.py
  django/templates/common/mbti_info.html
  django/templates/common/user_profile.html
  django/templates/index.html
  django/test_rec/views.py
Labels: 조원준, 전해리, 이나현

#46 [Model] BTS 모델(자체 제작) 성능 평가
  Content_based/bts_valid.ipynb
  Content_based/content_based_rec.py
  Data/DataProcessing/MBTI/character_hashtag.ipynb
  Data/DataProcessing/popular_character_top10.ipynb
Labels: 전해리, 채민수

#47 [Django] MBTI x 애니어그램 성격 정보 추가
  Data/DataProcessing/MBTI_Enneagram_tag_description.ipynb
  Data/DataProcessing/Movie_Select_Npop.ipynb
  Data/DataProcessing/ko_cha_info_processing.ipynb
  Utils/Pickle/MBTI_Enneagram_personality_tag.pickle
  Utils/Pickle/movie_random_select_final2.pickle
  Utils/Pickle/processed_ko_cha_info.pickle
  Utils/movie_select.py
  data/ko_character_info_df.pickle
  django/common/migrations/0004_batchtrain_model_name_alter_batchtrain_model_path.py
  django/common/models.py
  django/common/views.py
  django/config/settings.py
  django/static/css/index.css
  django/static/css/result_bootstrap.css
  django/static/css/result_movie.css
  django/static/css/style.css
  django/static/js/movie.js
  django/templates/base.html
  django/templates/common/detail_tmpuser.html
  django/templates/common/login.html
  django/templates/common/signup.html
  django/templates/common/user_profile.html
  django/templates/index.html
  django/templates/test_rec/footer.html
  django/templates/test_rec/result.html
  django/templates/test_rec/result_movie.html
  django/test_rec/migrations/0013_characterlike.py
  django/test_rec/migrations/0014_tmpuser_feedback.py
  django/test_rec/migrations/0015_tmpuser_annoy_recommend_movies_and_more.py
  django/test_rec/migrations/0016_tmpuser_annoy_bts_ratio.py
  django/test_rec/models.py
  django/test_rec/urls.py
  django/test_rec/views.py
Labels: 조원준, 전해리, 이나현

#49 [Airflow] 자동화 스크립트 제작
  Airflow/00_User_Recommend/Fake_User_Recommend.ipynb
  Airflow/00_User_Recommend/Real_user_Test.ipynb
  Airflow/00_User_Recommend/Real_user_to_train_inter.py
  BaseLine/Recbole_Validation_like_bts.ipynb
  BaseLine/args.py
  BaseLine/mvti_recommend.ipynb
  BaseLine/mvti_recommend.py
  BaseLine/mvti_recommend_to_DB.ipynb
  BaseLine/util.py
Labels: 조원준

#51 [Airflow] ADER Ensemble
  Airflow/02_Ensemble/Ensemble-py.ipynb
  Airflow/02_Ensemble/Ensemble.ipynb
  Airflow/02_Ensemble/mvti_ensemble.py
  BaseLine/util.py
Labels: 조원준

#52 [Develop] ADER 앙상블
  Airflow/02_Ensemble/Ensemble-py.ipynb
  Airflow/02_Ensemble/Ensemble.ipynb
  Airflow/02_Ensemble/mvti_ensemble.py
  BaseLine/util.py
Labels: 조원준

#53 [Airflow] LGCN 업데이트
  Airflow/02_Ensemble/Ensemble-py.ipynb
  Airflow/02_Ensemble/Ensemble.ipynb
  BaseLine/LGCN_update.py
  BaseLine/mvti_recommend.py
  interaction_model/validation.ipynb
Labels: 조원준, 정의준
