Repository boostcampaitech4lv23recsys2/level3_productserving-level3-recsys-08, pull requests merged in 2023-01, with the labels that each got.

#21 [Fastapi] 데이터 처리 및 FastAPI 프론트에 데이터 전달
  .gitignore
  Data/DataProcessing/Genre_Processing.ipynb
  Data/DataProcessing/MBTI_Character_duplicate_processing.ipynb
  Data/DataProcessing/MBTI_X_Enneagram_18x18_matrix.ipynb
  FastAPI/04_combine/engram_test.ipynb
  FastAPI/04_combine/main.py
  FastAPI/04_combine/movie.html
  FastAPI/04_combine/movie_poster.ipynb
  FastAPI/04_combine/result.html
  FastAPI/04_combine/result_bootstrap.html
  FastAPI/04_combine/result_movie.html
  FastAPI/04_combine/static/reset.css
  FastAPI/04_combine/static/result_bootstrap.css
  FastAPI/04_combine/static/test.css
  Utils/Pickle/MBTI_merge_movieLens_3229_movie.pickle
  Utils/Pickle/characterId_to_movieId.pickle
  Utils/Pickle/enneagram_question.pickle
  Utils/Pickle/movieid_to_poster_file.pickle
Labels: 조원준

#25 [Model] inter, side_info 영화 랜덤 추출 함수 작성 및 정리
  Data/DataProcessing/movie_select.ipynb
  Data/DataProcessing/movie_select.py
  django/config/settings.py
  django/db.sqlite3
  django/static/reset.css
  django/static/result_bootstrap.css
  django/static/test.css
  django/templates/test_rec/movie.html
  django/templates/test_rec/result.html
  django/templates/test_rec/result_bootstrap.html
  django/templates/test_rec/result_movie.html
  django/test_rec/urls.py
  django/test_rec/views.py
Labels: 전해리

#29 [django] Django-GCP 연결에 .env 적용
  Utils/Pickle/enneagram_similarity_075_099.pickle
  Utils/utils.py
  django/common/urls.py
  django/common/views.py
  django/config/settings.py
  django/static/infinite.min.js
  django/static/jquery.waypoints.min.js
  django/static/netflix.css
  django/static/noframework.waypoints.min.js
  django/static/reset.css
  django/static/result_bootstrap.css
  django/static/scroll.css
  django/static/spinner.js
  django/static/style.css
  django/static/test.css
  django/templates/common/user_profile.html
  django/templates/index.html
  django/templates/test_rec/base.html
  django/templates/test_rec/enneagram.html
  django/templates/test_rec/enneagram2.html
  django/templates/test_rec/enneagram3.html
  django/templates/test_rec/header.html
  django/templates/test_rec/main.html
  django/templates/test_rec/mbti.html
  django/templates/test_rec/movie.html
  django/templates/test_rec/nav.html
  django/templates/test_rec/result.html
  django/test_rec/admin.py
  django/test_rec/migrations/0006_rename_ennear_ans_tmpuser_ennea_ans1_and_more.py
  django/test_rec/migrations/0007_rename_ennea_ans1_tmpuser_ennear_ans_and_more.py
  django/test_rec/migrations/0008_rename_ennear_ans_tmpuser_ennea_ans1_and_more.py
  django/test_rec/migrations/0009_alter_tmpuser_prefer_movie_id_and_more.py
  django/test_rec/models.py
  django/test_rec/templatetags/__init__.py
  django/test_rec/templatetags/split_movieId_title.py
  django/test_rec/views.py
  requirements.txt
Labels: 조원준, 채민수, 이나현

#30 [Model] Side Info 추천 모델 개선
  Content_based/content_based_rec.py
  Data/DataProcessing/MBTI/MBTI_Character_duplicate_processing.ipynb
  Data/DataProcessing/MBTI/MBTI_X_Enneagram_18x18_matrix.ipynb
  Data/DataProcessing/MBTI/character_hashtag.ipynb
  Data/DataProcessing/MBTI/mbti_best_mbti.ipynb
  Data/DataProcessing/MBTI_Character_duplicate_processing.ipynb
  Data/DataProcessing/MBTI_X_Enneagram_18x18_matrix.ipynb
  Data/DataProcessing/Movie_select/final_movie_select.py
  Data/DataProcessing/Movie_select/movie_select.ipynb
  Data/DataProcessing/Movie_select/movie_select.py
  Data/DataProcessing/Movie_select/pca_plot.ipynb
  Data/DataProcessing/Movie_select/t-SNE_plot.ipynb
  Data/DataProcessing/movie_select.ipynb
  Data/DataProcessing/movie_select.py
  Data/DataProcessing/pca_plot.ipynb
  Utils/utils.py
  interaction_model/lgcn_interaction/lgcn_annoy.ipynb
Labels: 전해리, 채민수, 이나현

#31 [Data] 애니어그램 유사도 75~99로 조정, 캐릭터 ID 추가
  Content_based/content_based_FE.ipynb
  Data/DataProcessing/MBTI/MBTI_X_Enneagram_18x18_matrix.ipynb
Labels: 조원준, 채민수
